### ISSUE TITLE
lack of SQL syntax highlighting

### ISSUE THREAD

**Issue by lilgrassin** [petervaro/python#27]
In the regular python 2 package, there's highlighting of SQL command strings, but not in the python 3 package. It makes it rather hard to distinguish commands without it.

**Comment by petervaro** [comment]
SQL != python. If it was in the messy python2 syntax highlighter, that's already a bad thing, but it won't be in python3.

However, in the near future, I want to add support for special comments, like we've discussed in: https://github.com/petervaro/python/issues/19. So at some point, I can imagine, that adding a `#syntax_open:sql` and `#syntax_close:sql` (or something similar) will import the SQL highlighter and in between those two comments all strings will be highlighted as SQL lines.

On the other hand, my five cent here is: write them into separate files, add them the .sql extension (then you have the syntax highlight) and read those files on startup.
