### ISSUE TITLE
Quoted strings do not highlight SQL

### ISSUE THREAD

**Issue by GrayHatter** [petervaro/python#35]
Similar to how the Python syntax will highlight SQL keywords inside quoted strings. I'd like Python 3 to highlight them as well.

**Comment by petervaro** [comment]
SQL != Python, it has nothing to do with the base language the highlighter is all about. At some point optional highlighting will be added, for more details, read the [this](https://github.com/petervaro/python/issues/19) conversation!

**Comment by GrayHatter** [comment]
Of course it's your call mate, but do you think when within a quoted string, it decreases usability or read ablity? 

Per #27, if you'd be able to add that feature it would be a workable, but IMO still broken solution. Do you take donations for fixing issues?

**Comment by GrayHatter** [comment]
Just finished reading through the SO chat in #27 I think the `#syntax: {REGEX|SQL|HTML}` tag following the string is actually a great idea. So I retract the comment of it being broken.
