### ISSUE TITLE
Cannot print none-ascii characters in the build results

### ISSUE THREAD

**Issue by youfou** [petervaro/python#40]
Hi,

I can't print none-ascii characters in ST3.

For example:

If I run the code below

```python
#!/usr/bin/env python3
# coding: utf-8

import sys

print(sys.version)
print('汉字') # <-- raise here

```

I will get result like this

> 3.6.0 (default, Dec 24 2016, 08:01:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Traceback (most recent call last):
  File "/Users/z/Downloads/temp/test.py", line 7, in <module>
    print('\u6c49\u5b57')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
[Finished in 0.1s with exit code 1]
[shell_cmd: python3 -OO -u "/Users/z/Downloads/temp/test.py"]
[dir: /Users/z/Downloads/temp]
[path: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin]

----

By searching Google, I found solutions like this:
http://stackoverflow.com/questions/15166076/sublime-text-2-encoding-error-with-python3-build

----

Hope this can be fixed 😄 

----
And here's my system:
> OS: macOS Sierra (10.12.2)
ST: ST3 Build 3126
Py: 3.6.0 (installed with homebrew)

**Comment by petervaro** [comment]
and what does this have to do with my syntax highlighter?
