### ISSUE TITLE
The `in` in `[x for x in Y]` is not highlighted

### ISSUE THREAD

**Issue by SuyashLakhotia** [petervaro/python#43]
<img width="462" alt="screen shot 2017-12-17 at 4 01 12 pm" src="https://user-images.githubusercontent.com/8863065/34077990-97ba1bc8-e343-11e7-93eb-2ea7ae607706.png">

It would be great to have the `in` have the same color as `for` in the above statements! :)

**Comment by petervaro** [comment]
It is highlighted for almost 5 years now :)  Your problem is in your colour-theme!
